INSERT INTO fonction (id, nom) VALUES
('0', 'Chargé de sav'),
('1', 'DGD Chargé finance BLS/LVE'),
('2', 'Commercial'),
('3', 'Technicien Système Réseaux et Sécurité'),
('4', 'Chef Service Entretien'),
('5', 'Chauffeur Livreur'),
('6', 'Chauffeur de ligne'),
('7', 'Coordinateur FRET'),
('8', 'Chauffeur livreur commercial'),
('9', 'Chef d''Agence'),
('10', 'Chef Service Contre Remboursement'),
('11', 'Responsable logistique'),
('12', 'Chef d''Exploitation'),
('13', 'Directeur régional région est'),
('14', 'Manoeuvre'),
('15', 'Responsable commercial Réseau'),
('16', 'Chargé Recouvrement'),
('17', 'Chargé de  Clientèle'),
('18', 'Directeur Des Opérations'),
('19', 'Magasinier'),
('20', 'Chef Service Maintenance'),
('21', 'Chef Comptable'),
('22', 'Responsable Maintenance'),
('23', 'Aide Mécanicien'),
('24', 'Gestionnaire De Stock'),
('25', 'JARDINIER'),
('26', 'Directeur Régional Région Nord'),
('27', 'Resp Facturation et recouvrement'),
('28', 'Chef de Projet Recouvrement'),
('29', 'Responsable Pointeur'),
('30', 'Mécanicien'),
('31', 'DGA Pôle Support'),
('32', 'Resp performance commerciale back'),
('33', 'Responsable SMQ'),
('34', 'Responsable QHSE BLS-LVE'),
('35', 'Agent de sécurité'),
('36', 'Coordinateur Qualité'),
('37', 'lOGISTIC BUSINESS MANAGER'),
('38', 'Coordinateur Com et Exploitation Réseau'),
('39', 'Coordinateur Administratif  Réseau'),
('40', 'Coordinateur Gestion Réseau'),
('41', 'Responsable CR'),
('42', 'Responsable Cl Grands Comptes'),
('43', 'Adjoint Chef Ramassage'),
('44', 'Chef Service Expedition'),
('45', 'Assistante de Direction'),
('46', 'Directeur Régional Région Centre'),
('47', 'Chef du Département Informatique'),
('48', 'Che de Site AIN SEBAA'),
('49', 'Contrôleur Agences'),
('50', 'Chauffeur-Livreur (A)'),
('51', 'Chauffeur-Livreur (B)'),
('52', 'Chauffeur-Livreur (C)'),
('53', 'Pointeur (A)'),
('54', 'Taxateur (A)'),
('55', 'Manoeuvre (A)'),
('56', 'Aide Ramasseur (B)'),
('57', 'Manoeuvre (B)'),
('58', 'Taxateur (C)'),
('59', 'Pointeur (C)'),
('60', 'Resp Exploitation Messagerie Casablanca'),
('61', 'Gardien (C)'),
('62', 'Manoeuvre (C)'),
('63', 'Directeur Administratif et Financier'),
('64', 'Chef de Service Livraison'),
('65', 'Comptable Confirmé'),
('66', 'Directeur Commercial Messagerie'),
('67', 'Administratif ramassage'),
('68', 'Chef de Site'),
('69', 'Chef d''Equipe'),
('71', 'Chef de services généreaux'),
('72', 'Pompiste'),
('73', 'Directeur Affrettement'),
('74', 'Chef département Fret'),
('75', 'Responsable Planification Fret'),
('76', 'Responsable Sce administration des vente'),
('77', 'Responsable SAV'),
('78', 'Responsable Qualité'),
('79', 'Chef département comptabilité'),
('80', 'Administrateur Système'),
('81', 'Technicien IT'),
('82', 'Manutentionnaire'),
('83', 'Responsable magasin consommable+archives'),
('84', 'Standardiste'),
('85', 'Directeur Messagerie'),
('86', 'Opérateur de saisie'),
('87', 'Pointeur -taxateur'),
('88', 'Chef Service Réseau'),
('89', 'Commercial livreur'),
('90', 'Chef Service Maintenance'),
('91', 'Chef Service Ramassage'),
('92', 'Chef Service Réclamation'),
('93', 'Chef Service Réseau Ext'),
('94', 'Chef d''Agence Bis'),
('95', 'Chef d''Agence Casablanca'),
('96', 'Chef d''Atelier'),
('97', 'Responsable Matériel'),
('98', 'Administrateur Réseau'),
('99', 'Agent logistique'),
('100', 'Gestionnaire CR'),
('101', 'Assistante Qualité'),
('102', 'Gestionnaire de Trésorerie'),
('103', 'Trésorier'),
('104', 'Directeur Commercial Hors Casa'),
('105', 'Chef d''Atelier'),
('106', 'Responsable Opérations Logistiques'),
('107', 'Comptable Sénior'),
('108', 'Supérviseur'),
('109', 'Directeur Dvpt Logistique  & Transport'),
('110', 'Développeur Informatique'),
('111', 'Chef Département Exploitation'),
('120', 'Responsable Commercial Régional'),
('121', 'Président Directeur Général'),
('122', 'Administrateur ERP'),
('123', 'Responsable Contrôle de Gestion'),
('124', 'Contôleur de Gestion Commercial'),
('125', 'Directeur régional région est Bis'),
('133', 'Chef de Projets Logistiques'),
('134', 'DGA'),
('135', 'INVENTORISTE'),
('151', 'Coordinateur Exploitation'),
('199', 'Cordinateur QHSE'),
('200', 'GESTIONNAIRE FRET'),
('203', 'Coordinateur de réception'),
('204', 'ASSISTANT GDS'),
('210', 'Téléconseiller Enquête de Satisfaction'),
('221', 'RESPONSABLE GDS'),
('233', 'Responsable Marketing & Com'),
('300', 'Chef de projet SI'),
('301', 'Chef de Département ADV'),
('302', 'Technicien supérieur'),
('303', 'Chef De projets Dév Informatique'),
('304', 'Chargé Marketing Digital'),
('305', 'Chargé de la planification'),
('306', 'Relais RH'),
('308', 'Chargé d''Exploitation'),
('309', 'Responsable des Opérations KHYAYTA'),
('310', 'CD Normalisation & Certification'),
('311', 'Chef département Relation client'),
('312', 'Chef serv coord Adm Relais RH'),
('313', 'Chargé de la qualité et de la Métrologie'),
('314', 'Directeur Commercial Logistique'),
('315', 'Chargé de l''audit et contrôle de gestion'),
('316', 'Chef de Service CC Casablanca'),
('317', 'Key Account Manager'),
('318', 'Responsable management qualité'),
('319', 'Responsable des Etudes et Développement'),
('320', 'Technicien Help Desk'),
('321', 'Chargée du contre remboursement'),
('322', 'Help Desk'),
('331', 'Resp Comptabilité Générale et Fiscalité'),
('332', 'Directeur d''Exploitation Messagerie'),
('333', 'Adm système, réseau et télécom'),
('334', 'Responsable du Service Admin et Paie'),
('335', 'Chargée HSE'),
('336', 'Respo opérat Messagerie logistique Rabat'),
('337', 'Resp Trésorerie et Optimisation  Fin'),
('338', 'Chargée du Dév et Gestion de carrières'),
('339', 'Chef de Sce coordination Réseau'),
('340', 'Chargé des Assurances et Juridiques'),
('341', 'Chargée des Affaires Juridiques'),
('342', 'Responsable des Moyens Généreaux'),
('343', 'Chef de Service Ramassage'),
('344', 'Responsable des Opérations Frêt'),
('345', 'Chef d''Agence Casablanca Bis'),
('346', 'Chargé de l''Administration'),
('347', 'Chef Dép Adm du pers, paie et Relat soc'),
('348', 'Chargée de la Facturation'),
('349', 'Directeur des Opérations Logistiques'),
('350', 'Chef de Dép Gest du Parc et SS-Traitance'),
('351', 'Chargée du Call Center'),
('352', 'Resp Recouvrement & Juridique'),
('353', 'Chef de Projet Facturation'),
('354', 'Responsable facturation'),
('360', 'Chargé du Developpement RH'),
('362', 'Chargée du back office'),
('391', 'Business analyst'),
('399', 'Agent de Facturation'),
('400', 'Resp Paie et Développement RH'),
('401', 'Responsable Administration RH'),
('402', 'Responsable Paie'),
('403', 'Responsable Département Commercial'),
('407', 'Chargée RH'),
('423', 'ASSISTANTE COMMERCIAL'),
('444', 'Directeur Des Ressources Humaines'),
('445', 'Directeur RH & QHSE'),
('510', 'Assistante ADV'),
('511', 'Logisticien'),
('540', 'DGA Pôle Métier'),
('661', 'Responsable Travaux'),
('666', 'DGA POLE FINANCE'),
('700', 'Chargé de Paie et Développement RH'),
('701', 'Aide Technicien'),
('702', 'Contrôleur de Gestion Junior'),
('703', 'AGENT DE SAISIE'),
('704', 'CARISTE PINCE'),
('705', 'Responsable Ordonnancement'),
('775', 'Agent Administratif Expédition'),
('777', 'Agent Administratif Réception'),
('798', 'Contrôleur Expédition'),
('799', 'Contrôleur Réception'),
('800', 'Responsable ADV'),
('801', 'Comptable Fournisseur'),
('900', 'CARISTE'),
('901', 'Responsable Département Informatique'),
('902', 'Assistante SAV'),
('903', 'Responsable KPI-EXPLOITATION'),
('981', 'Contrôleur de gestion exploitation'),
('982', 'Responsable Recouvrement'),
('983', 'Chauffeur Commercial'),
('984', 'Chef d''équipe copacking'),
('999', 'Dir Compt Fin Audit Int & CG'),
('1000', 'Assistante Ressources Humaines'),
('1001', 'Développeur'),
('1002', 'Opérateur Call Center'),
('1003', 'Chargée de la Gestion Administrative'),
('1004', 'Technicien'),
('1005', 'Resp Organisation Frêt'),
('1006', 'Plannificateur'),
('1008', 'Sécurité'),
('1101', 'Responsable  E-Logistique'),
('1110', 'Sales Analyste'),
('1120', 'Responsable Opérations Messagerie Casa'),
('1201', 'Chargé de SAV'),
('1211', 'Responsable Commercial CASA'),
('1212', 'Chef Département Commercial'),
('2000', 'Responsanle Marketing'),
('5000', 'Directeur Central D''exploitation'),
('5555', 'Directeur Systèm d''information'),
('5556', 'Directeur Central Commercial'),
('5557', 'Secrétaire Général'),
('10001', 'Développeur Full stack'),
('10123', ''),
('99999', 'Chargé de compte client'),
('COM', 'RESPONSABLE COMMERCIAL'),
('CR', 'Gestionnaire CR Alphanum'),
('RH', 'Gestionnaire de paie');