INSERT INTO departement (id, nom) VALUES
(1, 'Service informatique'),
(2, 'Commercial Frêt'),
(3, 'Ressources Humaines'),
(4, 'Secrétariat'),
(5, 'Service Qualité'),
(6, 'Commercial'),
(7, 'Service Ramassage'),
(8, 'Exploitation'),
(9, 'Commercial Logistique'),
(10, 'Réseau'),
(11, 'Sce Caisse et Contre remboures'),
(12, 'Service Facturation / Recouvre'),
(13, 'Secrétariat Général'),
(14, 'Direction'),
(15, 'SI & Amélioration Continue'),
(16, 'Sce Audit/Contrôle de gestion'),
(17, 'Logistique'),
(18, 'Frêt'),
(19, 'SAV'),
(20, 'Service Généraux'),
(21, 'Messagerie'),
(22, 'Achats et Approvisionnement'),
(23, 'Service comptabilité'),
(24, 'Commercial Messagerie'),
(25, 'Maintenance'),
(26, 'Moyens Gérénaux'),
(27, 'Recouvrement'),
(28, 'Facturation'),
(30, 'Systèmes d''Information'),
(33, 'Call Center'),
(34, 'QSE'),
(35, 'Direction Générale'),
(36, 'Trésorerie et optimisation fin'),
(37, 'Comptabilité Gén et Fiscalité'),
(38, 'Finance, Audit Interne et CG'),
(39, 'Juridique et Assurance'),
(40, 'Standard'),
(41, 'Sales Analyste');