spring.application.name=MDMWEB
# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MDMWEB;encrypt=true;trustServerCertificate=true
spring.datasource.username=mdmuser2
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# --- PERFORMANCE FIX 1: STOP PRINTING SQL ---
spring.jpa.show-sql=false 
# Only turn this true if you are debugging a specific query failure

# --- PERFORMANCE FIX 2: REDUCE LOG NOISE ---
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF


spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1